server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: warehouse-provider-ware
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///warehouse_a?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka

feign:
  httpclient:
    enabled: true
    connection-timeout: 30000
  hystrix:
    enabled: true
